### ISSUE TITLE
Where is the dataset?

### ISSUE THREAD

**Issue by agn-7** [sismetanin/emosense-semeval2019-task3-emocontext#2]
Hello, 

Where are the training and testing sets?

**Comment by sismetanin** [comment]
Hi,

Data can be found in [the official LinkedIn group](https://www.linkedin.com/feed/update/urn:li:activity:6439879151053836288/) of the EmoContext competition. Unfortunately, we are unable to publish data in this repository due to the license agreement of the competition.

**Comment by agn-7** [comment]
Thanks for the response.

But this link is broken!

**Comment by sismetanin** [comment]
Is the LinkedIn site available in your country? What kind of error message did you receive then you were trying to access the site?

**Comment by agn-7** [comment]
Yes, fortunately, LinkedIn is accessible in my country.

Here's the error:

> It’s not you. It’s us. Try going back to the previous page or heading to your feed. You can also see our Help Center for more information.

**Comment by sismetanin** [comment]
Hm, then try to access the EmoContext group using [this link](https://www.linkedin.com/groups/12133338/). The information about datasets can be found in recent posts.

**Comment by agn-7** [comment]
I found it too, 

I sent the join request.

**Comment by agn-7** [comment]
At [there](https://competitions.codalab.org/competitions/19790#learn_the_details-data-set-format), mentioned that: 
> the training data release 

Do you know how could I download it?

**Comment by sismetanin** [comment]
Both [training](https://aka.ms/emocontextdata) and [test](https://www.linkedin.com/feed/update/urn:li:activity:6498105102199545856/) data are available in the LinkedIn group.

**Comment by agn-7** [comment]
Thanks, I downloaded it.

But my mean was about the mentioned link, (SemEval 2018) not 2019.

**Comment by agn-7** [comment]
I found that:

[SemEval 2018 sets](https://github.com/cbaziotis/ntua-slp-semeval2018/tree/master/datasets)
