### ISSUE TITLE
How long did training phase take on your model?

### ISSUE THREAD

**Issue by agn-7** [sismetanin/emosense-semeval2019-task3-emocontext#3]
I saw `197,824,434` parameter and `20` epochs in your jupyter file. Also, in `SemEval-2019 Task 3: EmoContext Contextual Emotion Detection in Text` paper mentioned that the training set is contained around 30,000 rows.
I think these are big values, so how long it takes for training in which resource for you?

**Comment by sismetanin** [comment]
I split training dataset into training and validation subsets, so the training phase was performed on 24128 samples. One training epoch takes about a minute on 2,9 GHz Intel Core i7, 16 GB 2133 MHz LPDDR3.

**Comment by agn-7** [comment]
So is my calculation correct?!

(24128 * 20 * 1) / (60 * 24) = 335 days

---
20 epochs for each samples which takes 1 minute

**Comment by agn-7** [comment]
I was wrong, you have only `385,000` trainable parameters, and that is not too big value.

And your training phase takes 20 mins only.
