### ISSUE TITLE
Is there the SemEval 2019 EmoContext baseline source code?

### ISSUE THREAD

**Issue by agn-7** [sismetanin/emosense-semeval2019-task3-emocontext#4]
Hi
I'm looking for the Baseline of this competition source code.

**Comment by agn-7** [comment]
Isn't this link?

https://github.com/L-Maybe/SemEval-2019-task3-EmoContext/blob/master/EmoContext/baseline.py

**Comment by sismetanin** [comment]
Yes, this is a baseline for EmoContext.
